---
name: Release

on:
  push:
    branches:
      - main

jobs:

  build_and_release:
    name: Build and release action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: bump the version
        id: bumper
        uses: tomerfi/version-bumper-action@1.1.3

      - name: Get versions
        id: versions
        uses: ./
        with:
          tag: ${{ steps.bumper.outputs.new_version }}
          prefix: v

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.bumper.outputs.new_version }}

      - name: Create Release
        id: create_release
        uses: nickatnight/releases-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: main
          tag: ${{ steps.bumper.outputs.new_version }}
