---
name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches-ignore:
      - main

  workflow_call:

jobs:
  lint_docker_file:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: lint docker file
        uses: rusty-actions/dockerfile-linter@v1
        with:
          dockerfile: .//Dockerfile
  test:
    name: Test script and action
    timeout-minutes: 10
    runs-on: ubuntu-latest
#    needs: [lint_docker_file]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: versions with prefix
        id: prefix
        uses: ./
        with:
          tag: "1.2.3"
          prefix: "v"

      - name: fail on bad major version with prefix
        if: steps.prefix.outputs.major_version != 'v1'
        run: exit 1

      - name: fail on bad minor version with prefix
        if: steps.prefix.outputs.minor_version != 'v1.2'
        run: exit 1

      - name: fail on bad patch version with prefix
        if: steps.prefix.outputs.patch_version != 'v1.2.3'
        run: exit 1

      - name: versions without prefix
        id: without
        uses: ./
        with:
          tag: "1.2.3"

      - name: fail on bad major version without prefix
        if: steps.without.outputs.major_version != '1'
        run: exit 1

      - name: fail on bad minor version without prefix
        if: steps.without.outputs.minor_version != '1.2'
        run: exit 1

      - name: fail on bad patch version without prefix
        if: steps.without.outputs.patch_version != '1.2.3'
        run: exit 1
